api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.index),
    path('categoria',views.categoria),
    path('marca',views.marca),
    path('producto',views.producto)
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorMarca/<int:marca_id>',views.productosPorMarca,name='productosPorMarca'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('pedidopagado',views.pedidopagado,name='pedidopagado'),
    path('carta', views.carta,name='carta'),
    path('contacto', views.contacto,name='contacto'),
    path('nosotros', views.nosotros,name='nosotros'),
    path('pedidos', views.pedidos,name='pedidos'),
    path('home', views.index,name='index')
]

web/models.py
from django.db import models

from cloudinary.models import CloudinaryField

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca,on_delete=models.RESTRICT)
    sku = models.CharField(max_length=20,null=True,default='01')
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField(null=True)
    peso = models.IntegerField(default=0,null=True)
    dimension = models.CharField(max_length=100,null=True,default='01')
    color = models.CharField(max_length=200,null=True,default='01')
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    #imagen = models.ImageField(upload_to='productos',blank=True)
    imagen = CloudinaryField('image')

    def __str__(self):
        return self.nombre

from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.CASCADE)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1,default='M')
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()

    def __str__(self):
        return self.dni

class Pedido(models.Model):
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )

    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)
    
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.producto.nombre

web/templates/carrito.html
{% extends 'layout2.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="carrito prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.categoria}}</a>
                        </p>
                        <h3><a href="product.html">{{ value.nombre }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Precio</p>
                        <p class="prod-li-price">${{value.precio}}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{value.cantidad}}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/carta.html
{% extends 'layout.html' %}
{% block content %}

  <main>
    <section class="title">
      <div class="container">
        <h2 class="title__text">Variedad de Helados</h2>
      </div>
    </section>

    <!-- <section class="special">
      <div class="container">
        <h3 class="special__title">Especialidad de la Casa</h3>
      
        <div class="special__wrapper">
          {% for prod in productos %}
          <div class="special__item">
            <div class="special__item-img">
              <img src="{{ prod.imagen.url }}" alt="Especial" loading="lazy">
            </div>
            <div class="special__item-info">
              <h3>{{prod.nombre}}</h3>
              <h4>S/{{prod.precio}}</h4>
            </div>
          </div>
          {% endfor %}

          
        </div>

      </div>
    </section> -->

    <section class="icecream">
      <div class="container">
        <h2 class="icecream__title">Helados más pedidos</h2>

        <div class="icecream__wrapper">
          {% for prod in productos %}
          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="{{ prod.imagen.url }}" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h2 style="color:black">{{prod.categoria.nombre}}</h2>
              <h3>{{prod.nombre}}</h3>
              <h4>S/{{prod.precio}}</h4> 
              <br>
              <a class="btn form__activo" href={% url 'web:agregarCarrito' prod.id %}>Carrito</a>
            </div>
          </div>
          {% endfor %}

          <!-- <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-durazno.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Durazno</h3>
              <h4>S/10</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-arandano.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Arándano</h3>
              <h4>S/10</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/image1.webp" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Frambuesa</h3>
              <h4>S/10</h4>
            </div>
          </div>
        </div>
      </div> -->
    </section>

    <!-- <section class="icecream">
      <div class="container">
        <h2 class="icecream__title">Helados de diferentes sabores</h2>

        <div class="icecream__wrapper">
          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-chocolate.webp" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Chocolate</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-menta2.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Menta</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-caramelo.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Caramelo</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-fresa.webp" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Fresa</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-vainilla.webp" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Vainilla</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-fresa-cono.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Helado de Cono - Fresa</h3>
              <h4>S/8</h4>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="icecream">
      <div class="container">
        <h2 class="icecream__title">Helados en vasito</h2>

        <div class="icecream__wrapper">
          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-frambuesa-vasito.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Arándanos</h3>
              <h4>S/12</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-vaso-chocolate-borde.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Oreo Chocolatoso</h3>
              <h4>S/12</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-vaso-tri-border.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Vainilla con Leche</h3>
              <h4>S/12</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-vaso-tres-border.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Chocolate y Vainilla</h3>
              <h4>S/12</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/helado-vaso-vainilla-borde.png" alt="Helado" loading="lazy">
            </div>
            <div class="icecream__item-info">
              <h3>Tri Sabor</h3>
              <h4>S/12</h4>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="icecream">
      <div class="container">
        <h2 class="icecream__title">Extras</h2>

        <div class="icecream__wrapper">
          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/cafe.png" alt="Helado">
            </div>
            <div class="icecream__item-info">
              <h3>Café</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/dona.png" alt="Helado">
            </div>
            <div class="icecream__item-info">
              <h3>Donnuts</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/Batidos.png" alt="Helado">
            </div>
            <div class="icecream__item-info">
              <h3>Batidos</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/granCono.png" alt="Helado">
            </div>
            <div class="icecream__item-info">
              <h3>Gran Cono</h3>
              <h4>S/8</h4>
            </div>
          </div>

          <div class="icecream__item">
            <div class="icecream__item-img">
              <img src="../static/img/fruta y helado.png" alt="Helado">
            </div>
            <div class="icecream__item-info">
              <h3>Fruta y helado</h3>
              <h4>S/8</h4>
            </div>
          </div>
        </div>
      </div>
    </section> -->

  </main>

{% endblock %}

web/templates/contacto.html
{% extends 'layout.html' %}
{% block content %}

  <main>
    <section class="info">
      <div class="container">
        <div class="info__wrapper">
          <div class="info__item">
            <div class="info__item-icon">
              <img src="../static/img/truck.svg" alt="Camión">
            </div>
            <h3>Envío gratis</h3>
            <p>A todo el Perú</p>
          </div>
          <div class="info__item">
            <div class="info__item-icon">
              <img src="../static/img/wall-clock-icon.svg" alt="Horario">
            </div>
            <h3>Horario</h3>
            <p>9AM - 7PM</p>
          </div>
          <div class="info__item">
            <div class="info__item-icon">
              <img src="../static/img/address-icon.svg" alt="Dirección">
            </div>
            <h3>Dirección</h3>
            <p>Magdalena 7485</p>
          </div>
          <div class="info__item">
            <div class="info__item-icon">
              <img src="../static/img/phone-icon.svg" alt="Llamada">
            </div>
            <h3>¡Llama ya!</h3>
            <p>164-2317</p>
          </div>
        </div>
      </div>
    </section>

    <section class="form">
      <div class="container">
        <h3 class="form__title">Contacto & consulta</h3>
      <div class="form__wrapper">
        <form>
          <div class="form__group">
            <label for="firstName">Nombres</label>
            <input type="text" name="first_name" id="firstName">
          </div>
          <div class="form__group">
            <label for="lastName">Apellidos</label>
            <input type="text" name="last_name" id="lastName">
          </div>
          <div class="form__group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
          </div>
          <div class="form__group">
            <label for="subject">Asunto</label>
            <input type="text" name="subject" id="subject" required>
          </div>
          <div class="form__group form__group-full">
            <label for="message">Mensaje</label>
            <textarea name="message" id="message" cols="30" rows="10" required></textarea>
          </div>
          <button id="enviar" type="submit" class="btn form__activo">Enviar</button>
        </form>
      </div>
    </section>
    <a id="mimail" href="mailto:rodriguez6191@hotmail.com"></a>
  </main>

{% endblock %}

web/templates/cuenta.html
{% extends 'layout2.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.first_name }} {{ user.last_name }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente|crispy }}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>    
{% endblock %}

web/templates/layout2.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tienda Codigo g15</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">


    {% include 'includes/header.html' %}

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

    {% include 'includes/footer.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

web/templates/login.html
{% extends 'layout2.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registrar & Autenticar</h1>
    <ul class="b-crumbs">
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Autenticar</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger"> {{error}}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registro</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Crear Cuenta">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

web/templates/nosotros.html
{% extends 'layout.html' %}
{% block content %}

  <main>
    <section class="history">
      <div class="container">
        <div class="history__wrapper">
          <div class="history__img">
            <img src="../static/img/helado-nosotros.jpg" alt="Foto">
          </div>
          <div class="history__info">
            <h3>Nuestra Historia</h3>
            <h4>Inicia en 2010</h4>
            <p>Bienvenido a Dolce Placer. Nos enorgullece brindar un servicio cálido y cordial, y poder prepara deliciosos helados para todos. Usamos ingredientes locales e importados frescos, para asegurarnos que
              tenga una experiencia gastronómica inolvidable.
              <br><br>
              Desde 2010, somos el lugar perfecto para degustar una gran variedad de diferentes sabores de helados entre dos, con amigos, fiestas o
              familiares. Con un entorno cómodo, precios asequibles
              y
              asientos para hasta 20 invitados. Le prometemos que tendrá una maravillosa experiencia juntos a sus seres queridos, no se arrepentirá.
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="goals">
      <div class="container">
        <div class="goals__info">
          <h3 class="goals__info-title">Visión a Futuro</h3>
          <p class="goals__info-text">Venderemos helados y bebidas deliciosas, de diferentes sabores que cumplan con los más altos criterios de calidad, al mismo tiempo que combinamos las tradiciones culinarias modernas, creativas y clásicas. Al mostrar calidez, amabilidad, eficiencia, habilidad, profesionalismo e integridad en nuestro trabajo, serviremos continuamente a nuestros consumidores con un servicio excepcional. Cada cliente que ingrese a nuestro local quedará impresionado por la experiencia que le ofreceremos en Dolce Placer y luego quedar emocionados en volver.</p>
        </div>
        <div class="goals__img-wrapper">
          <div class="goals__img1">
            <img src="../static/img/goals1.jpg" alt="Foto">
          </div>
          <div class="goals__img2">
            <img src="../static/img/goals2.jpg" alt="Foto">
          </div>
          <div class="goals__img3">
            <img src="../static/img/goals3.jpg" alt="Foto">
          </div>
        </div>
      </div>
    </section>
  </main>

{% endblock %}

web/templates/pedido.html
{% extends 'layout2.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {% for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{ detalle.producto.imagen.url }}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{ detalle.producto.nombre }}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}